import type { Metadata } from "next";
import { Archivo_Black, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const archivo = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-archivo",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "A R T E N G I N E // PORTFOLIO",
  description: "Generated by ArtEngine v0.1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${jetbrains.variable} font-body bg-background text-foreground antialiased`}
      >
        <div className="fixed inset-0 pointer-events-none z-50 border-[1px] border-white/5 opacity-50 mix-blend-overlay"></div>
        {children}
      </body>
    </html>
  );
}
